---
title: Book Review - Spiritual Warfare And Divine Mercy by Fr. Ken Geraci, CPM
date: 2024-11-12 22:26:49
layout: post
lang: en
tags: [catholic, prayer, spiritual warfare]
draft: false
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

Today, I am going to be reviewing the book /Spritual Warfare and Divine Mercy/
by Fr. Ken Geraci, CPM.  I hope you enjoy!

First of all, I just wanted to say that Fr. Geraci is a personal inspiration to
me because, like me, he journeyed from The Church, to agnosticism, to
Non-Denominatioal, back to The Church. I am sure many of his readers are
thankful he followed this path, as we can relate!

Second, I want to give an overview of the important topics discussed in the
book. First, he talks generally about prayer, spiritual warfare, and
confession. Then is the meat of the book: the three Divine Mercy weapons.

1. The Divine Mercy Image
2. The Divine Mercy Feast Day
3. The Divine Mercy Chaplet

After these, he talks about why the rosary and praying the Spiritual Mass are
also great weapons in the Divine Fight.

Overall, I would say this is a great book to pick up if you are looking to add
more spiritual weapons in your arsenal, in particular the Divine Mercy Chaplet
(which can be found on YouTube: [[https://youtu.be/5pdnzUjmkzA?si=lHW3Gwj3lzciAqrJ][Divine Mercy Chaplet]]).  I give it:

4/5 Stars.
