---
title: We Discern The Words Of Paul
date: 2026-03-19 10:29:10
layout: post
lang: en
tags: [catholic]
draft: false
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

As Christians, we understand that The Bible (in a sense) is perfect, because its creation was
guided by the Hand of God.  However, that doesn't mean that every single word in it is literally
true.

The words of The Bible were also written by men.  What this means is that, there are some parts of
The Bible that are not to be taken as (pun intended) gospel.

For example, many would have you believe (either) that the words of Paul are inexorably true (such
as The Protestants).  Many others (including the so-called Mahdi) would have you discount totally
the words of Paul.

We, as Christians, are taught instead to use DISCERNMENT when reading the words of Paul.  Where
they differ or contradict the words of Jesus (such as that Faith, without Works, is enough for us),
we must refer back to the words of Jesus Christ.

Jesus teaches that we must love our neighbor, and that he who judges his fellow man will be
measured by the same stick.  These words point to the fact that it is NOT Faith alone that saves:
we must also do Works.  Namely, to enter the Kingdom of Heaven, we must do our best to emulate
Jesus Christ through our actions in the present world.
